spring:
  mvc:
    hiddenmethod:
      filter: # 开启 delete put patch 请求 
        enabled: true
  # static-path-pattern: /res/**  # 静态资源url前缀
  # resources: 
  #   static-locations: [classpath:/haha/] # 自定义静态资源文件夹
  