spring:
  profiles:
    active: m1

# 文档块
---
spring:
  profiles: m1
server:
  port: 8081
---
spring:
  profiles: m2
server:
  port: 8082
---
spring:
  profiles: m3
server:
  port: 8083

# 还可以使用命令行
# java -jar target/demo-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev

# 虚拟机参数
# -Dspring.profiles.active=dev
