spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB


    jdbc:
        template:
            query-timeout: 3


    datasource:
        url: jdbc:mysql://localhost:3306/jdbc?useSSL=false&useUnicode=true&characterEncoding=utf-8
        username: root
        password: admin
        driver-class-name: com.mysql.jdbc.Driver

        druid:
            filters: wall,stat
            aop-patterns: com.spring.l05_web_admin.*
            stat-view-servlet:
                enabled: true
                login-username: admin
                login-password: 111111 
                reset-enable: false

            web-stat-filter:
                enabled: true
                url-pattern: /*
                exclusions: /druid/*,/css/*,/fonts/*,/images/*,/js/*,/favicon.ico

            filter: 
                stat:
                    slow-sql-millis: 100
                    log-slow-sql: true
                    enabled: true
                wall:
                    enabled: true
                    config:
                        drop-table-allow: false
    redis:
        host: 127.0.0.1
        port: 6379 #Redis服务器连接端口
        password: 
        timeout: 30000 #连接超时时间（毫秒）
        client-type: jedis # 使用 jedis
        jedis:
        # lettuce:
            pool:
                max-active: 10
                min-idle: 5